filters:
  - label: âœ… Test
    regexs:
      - /í…ŒìŠ¤íŠ¸/i
    events: [issues, pull_request]
    targets: [title, branch]

  - label: ğŸ¨ Style
    regexs:
      - /ìŠ¤íƒ€ì¼/i
    events: [issues, pull_request]
    targets: [title, comment, branch]

  - label: ğŸ¨ Style
    regexs:
      - /í¬ë§·íŒ…/i
    events: [issues, pull_request]
    targets: [title, comment, branch]

  - label: ğŸ”¨ Refactor
    regexs:
      - /ë¦¬íŒ©í„°ë§/i
    events: [issues, pull_request]
    targets: [title, comment, branch]

  - label: ğŸš€ Performance
    regexs:
      - /ì„±ëŠ¥/i
    events: [issues, pull_request]
    targets: [title, comment, branch]

  - label: ğŸ“œ Logging
    regexs:
      - /ë¡œê¹…/i
    events: [issues, pull_request]
    targets: [title, comment, branch]

  - label: ğŸ”„ Integration
    regexs:
      - /í†µí•©/i
    events: [issues, pull_request]
    targets: [title, comment, branch]

  - label: âœ¨ Feature
    regexs:
      - /CRUD/i
    events: [issues, pull_request]
    targets: [title, comment, branch]

  - label: ğŸŒ Deploy
    regexs:
      - /ë””í”Œë¡œì´/i
    events: [issues, pull_request]
    targets: [title, comment, branch]

  - label: ğŸ›  Dependency
    regexs:
      - /ì˜ì¡´ì„±/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]

  - label: ğŸ”§ Build
    regexs:
      - /ë¹Œë“œ/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]

  - label: ğŸ BugFix
    regexs:
      - /ë²„ê·¸í”½ìŠ¤/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]

  - label: ğŸ¤– Automation
    regexs:
      - /ì˜¤í† ë©”ì´ì…˜/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]

  - label: ğŸ” Authentication
    regexs:
      - /ì¸ì¦/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]

  - label: ğŸ—‚ Architecture
    regexs:
      - /ì•„í‚¤í…ì²˜/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]

  - label: 1ï¸âƒ£ Liberty52 Main Service
    regexs:
      - /ë©”ì¸/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]

  - label: 1ï¸âƒ£ Liberty52 Main Service
    regexs:
      - /Main/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]

  - label: 1ï¸âƒ£ Liberty52 Main Service
    regexs:
      - /MAIN/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]

  - label: 2ï¸âƒ£ Liberty52 Auth Service
    regexs:
      - /Auth/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]

  - label: 2ï¸âƒ£ Liberty52 Auth Service
    regexs:
      - /AUTH/i
    events: [ issues, pull_request ]
    targets: [ title, comment, branch ]
